### ISSUE TITLE
Support for Angular / Typescript ?

### ISSUE THREAD

**Issue by dota2Pro** [anvaka/panzoom#108]
First of all Awesome Library! 
I was wondering are there any plans to have typescript definitions in this so that this can be used with the new Angular Framework ?

It would be great to have that since lot of people are using Angular now a days

**Comment by rbonomo** [comment]
Does the new Angular not support using standard JS libraries? And I'd say that Angular isn't the future of web dev. It will go in time. If you use JS right, you don't need libraries / frameworks to manage state and rendering of components.

**Comment by dota2Pro** [comment]
> Does the new Angular not support using standard JS libraries? And I'd say that Angular isn't the future of web dev. It will go in time. If you use JS right, you don't need libraries / frameworks to manage state and rendering of components.

Does the new Angular not support using standard JS libraries -> it does, but in a hacky way they compel you to use typescript instead of JS. Well in my opinion Typescript is cool because its syntax is same as Java, so you don't need to learn two languages also gives you error on compile time instead of run time etc.But ya JS will always be there.

**Comment by anvaka** [comment]
type definitions are here: https://github.com/anvaka/panzoom/blob/master/index.d.ts - are they not configured properly?

**Comment by dota2Pro** [comment]
> type definitions are here: https://github.com/anvaka/panzoom/blob/master/index.d.ts - are they not configured properly?

Thanks, I never noticed Angular in the documentation so I thought type definitions weren't there,
I am able to see it now https://stackblitz.com/edit/angular-nrof7z?file=src%2Fapp%2Fhello.component.ts

**Comment by dota2Pro** [comment]
> type definitions are here: https://github.com/anvaka/panzoom/blob/master/index.d.ts - are they not configured properly?

Do you know why `import panzoom from 'panzoom';` works and `import {panzoom} from 'panzoom';` doesn't ?

**Comment by anvaka** [comment]
Those are two different statements. One suggests to import default exported value from `panzoom` module. The other one asks to import value that is called `panzoom` from a `panzoom` module. Since we are not exporting non-default value - the `import {panzoom} from 'panzoom'` statement fails.

Here is a stackoverflow question that is similar in nature: https://stackoverflow.com/questions/48537180/difference-between-import-something-from-somelib-and-import-something-from

**Comment by ShinTorisawa** [comment]
Could you please tell me the correct way to import panzoom version 9.4.3 in ESM format using TypeScript 2.0?

I thought that panzoom only supports CommonJS format and not ESM format, because in the package.json file, it is written "main": "index.js" and there is no "module" field.

However, I am confused because there is a post here that says import panzoom from 'panzoom' works, which is an ESM format import method. Does panzoom officially support ESM format?

After much trial and error, I found that unless I add the code export default panzoom; to the end of panzoom/dist/panzoom*.js, it does not work with the ESM format import statement.

So I thought it was strange and came to ask the question at the beginning.
