### ISSUE TITLE
resume() not working on mobile phones.

### ISSUE THREAD

**Issue by naseemshah** [anvaka/panzoom#188]
After pausing the Panzoom, i tried calling resume(). Works on PC Browsers. Not in Mobile Broswers. Once paused, it's stuck.

**Comment by anvaka** [comment]
Thank you for reporting this. While I cannot reproduce this with my test setup, I checked the code and see one potential reason for the described behavior.

Please grab the latest version `v9.2.4` and let me know if the issue is still there. I hope it is not, but if I missed something else - would you be able to put a quick jsbin script to help reproduce it?

**Comment by naseemshah** [comment]
Thanks man! Works prefectly! Thank you for fixing so instantly. So what caused this problem?

**Comment by anvaka** [comment]
Glad to hear it worked!

There was a state property that wasn't cleared correctly if `pause()` was called while the touch event was in progress. See [`touchInProgress`](https://github.com/anvaka/panzoom/commit/439c613c1918a8a95c09469ed9a422dc3881decb#diff-168726dbe96b3ce427e7fedce31bb0bcR786)
