### ISSUE TITLE
Zooming in and out repeatedly causes frame rates to become lower and lower

### ISSUE THREAD

**Issue by S41L0R** [anvaka/panzoom#231]
Hey! I have this attached to a div with a grid of PNG images inside, and it works great except for some lag that is caused if I zoom in all the way and then out again repeatedly. Also, another small issue is that the images in my grid seem to get 1 px of padding, so I end up seeing almost a white grid overlayed.

**Comment by S41L0R** [comment]
This is most likely caused by vram usage, as I can move it so that only a few images are still in frame and it works fine. Also I am running on limited vram at the moment.

**Comment by anvaka** [comment]
What you are describing is typical symptom of a memory leak issue. However without seeing an example to reproduce it - it's hard to guess where the issue is - it could be in the browser/os itself, or it could be in javascript code (e.g. if you repeatedly subscribe to events without releasing them, and/or do some sort of memory allocation)

**Comment by S41L0R** [comment]
Yeah, so I'm not having quite the same issue anymore, when I zoom in and out, I still get low fps, but it doesn't last very long at all before it goes back to normal. 

When it comes to what I have set up though as far as js, I just have event listeners connected to each image, and nothing is fired on zoom in.

* Also, this is all in electron if that matters

I am going to close this issue as the performance issues don't stay anymore.
