### ISSUE TITLE
panzoom support object?

### ISSUE THREAD

**Issue by strelkovandrey** [anvaka/panzoom#25]
Sorry for my bad english...

Good day, I try use this awesome solution for my svg map in page.
But my map is not inline svg, I attach to index.html how object
Here is code of my html

All running fun, but I can pan and zoom only when my cursor on body zone, e.g. if cursor on svg, I can't pan and zoom

```html
<html>
<head>
  <style type="text/css">  
    body,html {
      margin: 0;
      padding: 0;
      position: fixed;
      width: 100%;
      height: 100%;
      background: green;
    }   
    .map {
      width: 50%;
      height: 50%;
    }                                                                               	
  </style>
</head>

<body>
  <object type="image/svg+xml" data="svg/map.svg" width="100%" height="100%" class="map" id="zoomable"</object>

  <script src='js/panzoom.js'></script>
  <script>
    var area = document.getElementById('zoomable')
    panzoom(area)
  </script>
</body>

</html>
```

Where is my mistake?

**Comment by anvaka** [comment]
Uhm, I'm not sure how this should work with `object` tag. Can you use `svg` instead?

**Comment by anvaka** [comment]
I'm going to close this, as there is no response. Please let me know if need more support.

**Comment by perskes** [comment]
Hey, this very same issue occurs for me, and there are only two issues in regards to the "object" tag, so I am piggy backing instead of opening a new one.

What OP describes also applies to me.

I have a div and an object tag inside this div.
The object tag loads the SVG.

This is the JS I use to make panzoom work with the object tag (it is hacky, but it kinda works).

```
var element;
// just grab a DOM element
document.querySelector('#svgWindow').addEventListener("load", function() {
  element = this.getSVGDocument().children[0].querySelector("#mainLayer");

  // And pass it to panzoom
  panzoom(element, {
    smoothScroll: true,
    maxZoom: 40,
    minZoom: 5
  })
})
```


Now, the issue is, that you can not drag the svg directly, but rather click the svg, move the mouse to a new position outside the div/object tag, and THEN it jumps to that position and gets dragged.

Please see the attached GIF.

It has to do with the object-tag, using SVG directly is not my preferred solution, to be honest, but I tested it and it works.
You actually apply the transformation to the svg if its in the object tag, just in case you are wondering.

![ezgif-7-71379053bcc5](https://user-images.githubusercontent.com/20817724/98127133-a2414600-1eb6-11eb-82ad-84c6543cb468.gif)

Any pointers to what part of the library might be responsible here?
I'd love to tinker around, but you might be able to point me into the right direction.
