### ISSUE TITLE
Apply Pan Zoom features to an svg within an object tag.

### ISSUE THREAD

**Issue by ACQuo1001** [anvaka/panzoom#75]
Is it possible to apply the pan zoom features when you load an svg on a web page thorugh an object tag? 

I keep getting the same error: Uncaught Error: Cannot create panzoom for the current type of dom element

Is this something that can be done and I'm just doing something wrong? Or can the Pan/Zoom features only be applied when you load an svg directly in an html file? 

Please let me know.

Thank you,

**Comment by anvaka** [comment]
Oh, I haven't tried that. 

The error you've mentioned [originates here](https://github.com/anvaka/panzoom/blob/1231157ea167a3afe970507d7c3669cef5ad7b64/index.js#L44) - basically we don't know how to do the transforms on an object tag.

I'm not very familiar with `<object>` API but have huge doubts it would be possible due to security reasons. That said, I might be wrong. If someone can implement a transform controller for `object` then panzoom should be usable there as well. For the reference see
* [dom controller](https://github.com/anvaka/panzoom/blob/master/lib/domController.js)
* [svg controller](https://github.com/anvaka/panzoom/blob/master/lib/svgController.js)
* [webgl controller in w-gl library](https://github.com/anvaka/w-gl/blob/master/src/scene.js#L198)
